version: '3'

services:
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - '5000:5000'
    environment:
      - FLASK_ENV=development
    depends_on:
      - frontend
